### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by claudiaanjos** [RafaelCava/RafaelCava#1]
Oi Rafael! Tudo bem?

Adorei o seu readme!
Posso fazer algumas sugestões para você?

No tópico "Linguagens de Programação":
- os itens Git, HTML, CSS, Sass e MySQL não são linguagens de programação.

No "jogo da cobrinha":
- tente colocar o seu user, porque o quadro de contribuições aparece como sendo o da Rafa Ballerini.

Seu repositório está ótimo!

**Comment by RafaelCava** [comment]
Oi Claudia! tudo sim,

Muito obrigado vou corrigir esses detalhes.
